// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             (unknown)
// source: v1/opencv.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOpenCVServiceWarpPerspective = "/v1.OpenCVService/WarpPerspective"

type OpenCVServiceHTTPServer interface {
	WarpPerspective(context.Context, *WarpPerspectiveRequest) (*Image, error)
}

func RegisterOpenCVServiceHTTPServer(s *http.Server, srv OpenCVServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/opencv:WarpPerspective", _OpenCVService_WarpPerspective0_HTTP_Handler(srv))
}

func _OpenCVService_WarpPerspective0_HTTP_Handler(srv OpenCVServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WarpPerspectiveRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOpenCVServiceWarpPerspective)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.WarpPerspective(ctx, req.(*WarpPerspectiveRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Image)
		return ctx.Result(200, reply)
	}
}

type OpenCVServiceHTTPClient interface {
	WarpPerspective(ctx context.Context, req *WarpPerspectiveRequest, opts ...http.CallOption) (rsp *Image, err error)
}

type OpenCVServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewOpenCVServiceHTTPClient(client *http.Client) OpenCVServiceHTTPClient {
	return &OpenCVServiceHTTPClientImpl{client}
}

func (c *OpenCVServiceHTTPClientImpl) WarpPerspective(ctx context.Context, in *WarpPerspectiveRequest, opts ...http.CallOption) (*Image, error) {
	var out Image
	pattern := "/opencv:WarpPerspective"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOpenCVServiceWarpPerspective))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
