// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: open-scanner-be/v1/opencv.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width    int32  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height   int32  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Channels int32  `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	Data     []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_open_scanner_be_v1_opencv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_open_scanner_be_v1_opencv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_open_scanner_be_v1_opencv_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Image) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Image) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *Image) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Point2F struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Point2F) Reset() {
	*x = Point2F{}
	if protoimpl.UnsafeEnabled {
		mi := &file_open_scanner_be_v1_opencv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point2F) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point2F) ProtoMessage() {}

func (x *Point2F) ProtoReflect() protoreflect.Message {
	mi := &file_open_scanner_be_v1_opencv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point2F.ProtoReflect.Descriptor instead.
func (*Point2F) Descriptor() ([]byte, []int) {
	return file_open_scanner_be_v1_opencv_proto_rawDescGZIP(), []int{1}
}

func (x *Point2F) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point2F) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Size2F struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  float32 `protobuf:"fixed32,1,opt,name=width,proto3" json:"width,omitempty"`
	Height float32 `protobuf:"fixed32,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *Size2F) Reset() {
	*x = Size2F{}
	if protoimpl.UnsafeEnabled {
		mi := &file_open_scanner_be_v1_opencv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Size2F) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size2F) ProtoMessage() {}

func (x *Size2F) ProtoReflect() protoreflect.Message {
	mi := &file_open_scanner_be_v1_opencv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size2F.ProtoReflect.Descriptor instead.
func (*Size2F) Descriptor() ([]byte, []int) {
	return file_open_scanner_be_v1_opencv_proto_rawDescGZIP(), []int{2}
}

func (x *Size2F) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Size2F) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type WarpPerspectiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcImage   *Image     `protobuf:"bytes,1,opt,name=srcImage,proto3" json:"srcImage,omitempty"`
	SrcCorners []*Point2F `protobuf:"bytes,2,rep,name=srcCorners,proto3" json:"srcCorners,omitempty"`
	DestSize   *Size2F    `protobuf:"bytes,3,opt,name=destSize,proto3" json:"destSize,omitempty"`
}

func (x *WarpPerspectiveRequest) Reset() {
	*x = WarpPerspectiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_open_scanner_be_v1_opencv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WarpPerspectiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarpPerspectiveRequest) ProtoMessage() {}

func (x *WarpPerspectiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_open_scanner_be_v1_opencv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarpPerspectiveRequest.ProtoReflect.Descriptor instead.
func (*WarpPerspectiveRequest) Descriptor() ([]byte, []int) {
	return file_open_scanner_be_v1_opencv_proto_rawDescGZIP(), []int{3}
}

func (x *WarpPerspectiveRequest) GetSrcImage() *Image {
	if x != nil {
		return x.SrcImage
	}
	return nil
}

func (x *WarpPerspectiveRequest) GetSrcCorners() []*Point2F {
	if x != nil {
		return x.SrcCorners
	}
	return nil
}

func (x *WarpPerspectiveRequest) GetDestSize() *Size2F {
	if x != nil {
		return x.DestSize
	}
	return nil
}

var File_open_scanner_be_v1_opencv_proto protoreflect.FileDescriptor

var file_open_scanner_be_v1_opencv_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6f, 0x70, 0x65, 0x6e, 0x2d, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2d, 0x62,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x25, 0x0a, 0x07,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x66, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x79, 0x22, 0x36, 0x0a, 0x06, 0x53, 0x69, 0x7a, 0x65, 0x32, 0x66, 0x12, 0x14, 0x0a,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x94, 0x01, 0x0a, 0x16,
	0x57, 0x61, 0x72, 0x70, 0x50, 0x65, 0x72, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x73, 0x72, 0x63, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x52, 0x08, 0x73, 0x72, 0x63, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a,
	0x0a, 0x73, 0x72, 0x63, 0x43, 0x6f, 0x72, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x66, 0x52, 0x0a,
	0x73, 0x72, 0x63, 0x43, 0x6f, 0x72, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x26, 0x0a, 0x08, 0x64, 0x65,
	0x73, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x32, 0x66, 0x52, 0x08, 0x64, 0x65, 0x73, 0x74, 0x53, 0x69,
	0x7a, 0x65, 0x32, 0x6d, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x56, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x0f, 0x57, 0x61, 0x72, 0x70, 0x50, 0x65, 0x72, 0x73, 0x70,
	0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x61, 0x72, 0x70,
	0x50, 0x65, 0x72, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x09, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x22, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x3a, 0x01, 0x2a, 0x22, 0x17, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63,
	0x76, 0x3a, 0x57, 0x61, 0x72, 0x70, 0x50, 0x65, 0x72, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x68, 0x75, 0x73, 0x65, 0x69, 0x6e, 0x6e, 0x61, 0x73, 0x68, 0x72, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x2d, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2d, 0x62, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x6f, 0x70, 0x65, 0x6e, 0x2d, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2d, 0x62, 0x65, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_open_scanner_be_v1_opencv_proto_rawDescOnce sync.Once
	file_open_scanner_be_v1_opencv_proto_rawDescData = file_open_scanner_be_v1_opencv_proto_rawDesc
)

func file_open_scanner_be_v1_opencv_proto_rawDescGZIP() []byte {
	file_open_scanner_be_v1_opencv_proto_rawDescOnce.Do(func() {
		file_open_scanner_be_v1_opencv_proto_rawDescData = protoimpl.X.CompressGZIP(file_open_scanner_be_v1_opencv_proto_rawDescData)
	})
	return file_open_scanner_be_v1_opencv_proto_rawDescData
}

var file_open_scanner_be_v1_opencv_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_open_scanner_be_v1_opencv_proto_goTypes = []interface{}{
	(*Image)(nil),                  // 0: v1.Image
	(*Point2F)(nil),                // 1: v1.Point2f
	(*Size2F)(nil),                 // 2: v1.Size2f
	(*WarpPerspectiveRequest)(nil), // 3: v1.WarpPerspectiveRequest
}
var file_open_scanner_be_v1_opencv_proto_depIdxs = []int32{
	0, // 0: v1.WarpPerspectiveRequest.srcImage:type_name -> v1.Image
	1, // 1: v1.WarpPerspectiveRequest.srcCorners:type_name -> v1.Point2f
	2, // 2: v1.WarpPerspectiveRequest.destSize:type_name -> v1.Size2f
	3, // 3: v1.OpenCVService.WarpPerspective:input_type -> v1.WarpPerspectiveRequest
	0, // 4: v1.OpenCVService.WarpPerspective:output_type -> v1.Image
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_open_scanner_be_v1_opencv_proto_init() }
func file_open_scanner_be_v1_opencv_proto_init() {
	if File_open_scanner_be_v1_opencv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_open_scanner_be_v1_opencv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_open_scanner_be_v1_opencv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point2F); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_open_scanner_be_v1_opencv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Size2F); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_open_scanner_be_v1_opencv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WarpPerspectiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_open_scanner_be_v1_opencv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_open_scanner_be_v1_opencv_proto_goTypes,
		DependencyIndexes: file_open_scanner_be_v1_opencv_proto_depIdxs,
		MessageInfos:      file_open_scanner_be_v1_opencv_proto_msgTypes,
	}.Build()
	File_open_scanner_be_v1_opencv_proto = out.File
	file_open_scanner_be_v1_opencv_proto_rawDesc = nil
	file_open_scanner_be_v1_opencv_proto_goTypes = nil
	file_open_scanner_be_v1_opencv_proto_depIdxs = nil
}
