name: "Release to Development"
concurrency:
  group: dev
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v2
      - name: Replace env placeholders
        run: |
          sed -i "s/#{GITHUB_SHA}/$GITHUB_SHA/g" ./.k8s/dev/scanme-backend-depl.yaml
          sed -i "s/#{VERSION}/${GITHUB_SHA::7}/g" ./Makefile
      - name: Build and push docker image
        run: |
          IMAGE=registry.registry.svc.cluster.local/scanme-backend

          docker pull ${IMAGE}:latest-dev || true

          docker buildx build --push -t ${IMAGE}:${GITHUB_SHA}-dev -t ${IMAGE}:latest-dev \
            --cache-to type=inline --cache-from type=registry,ref=${IMAGE}:latest-dev .
      - name: Deploy to Dev Cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: |
            kubectl apply -f ./.k8s/dev/scanme-backend-depl.yaml
            kubectl apply -f ./.k8s/dev/scanme-backend-svc.yaml
            kubectl apply -f ./.k8s/dev/scanme-backend-ingress-http.yaml