name: "Release to Production"
concurrency:
  group: prod
  cancel-in-progress: true

on:
  push:
    tags: 
    - '*-production'

jobs:
  deploy:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v2
      - name: Set REALEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Replace env placeholders
        run: |
          sed -i "s/#{VERSION}/$RELEASE_VERSION/g" ./Makefile
          sed -i "s/#{RELEASE_VERSION}/$RELEASE_VERSION/g" ./.k8s/prod/scanme-backend-depl.yaml
      - name: Build and push docker image
        run: |
          docker build -t registry.registry.svc.cluster.local/scanme-backend:$RELEASE_VERSION .
          docker push registry.registry.svc.cluster.local/scanme-backend:$RELEASE_VERSION
      - name: Deploy to Production Cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: |
            kubectl apply -f ./.k8s/prod/scanme-backend-depl.yaml
            kubectl apply -f ./.k8s/prod/scanme-backend-svc.yaml
            kubectl apply -f ./.k8s/prod/scanme-backend-ingress-http.yaml